version: '3.8'
services:
  db:
    image: postgres:15.2-alpine
    restart: always
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5433:5432'
    volumes: 
      - mc-db:/var/lib/postgresql/data
volumes:
  mc-db:
    driver: local